apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-web
  template:
    metadata:
      labels:
        app: docker-web
    spec:
      containers:
      - name: docker-web
        image: tafazzul72/docker-web:latest  # Use your Docker Hub image
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: "mysql-db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "Tafazzul@72"
        - name: MYSQL_DATABASE
          value: "registration"