apiVersion: v1
kind: Service
metadata:
  name: docker-web-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Port to access the service
  selector:
    app: docker-web