version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Tafazzul@72"  # Set a secure password here
      MYSQL_DATABASE: registration
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: